/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DetailsIndexImport } from './routes/details/index'
import { Route as BlogIndexImport } from './routes/blog/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DetailsIndexRoute = DetailsIndexImport.update({
  path: '/details/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/details/': {
      id: '/details/'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/details': typeof DetailsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/details': typeof DetailsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/details/': typeof DetailsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/details'
  id: '__root__' | '/' | '/blog/' | '/details/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DetailsIndexRoute: typeof DetailsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DetailsIndexRoute: DetailsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog/",
        "/details/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/details/": {
      "filePath": "details/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
